[project]
name = "qiskit-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "===3.13.12"
dependencies = [
    "fastapi>=0.131.0",
    "qiskit>=2.3.0",
    "uvicorn>=0.41.0",
]
